require 'open-uri'
require 'nokogiri'
require 'pry'
require 'date'
require 'sqlite3'

require_relative './tempestry_pattern/version'
require_relative './tempestry_pattern/color'
require_relative './tempestry_pattern/scraper'
require_relative './tempestry_pattern/pattern'
require_relative './tempestry_pattern/cli'
